### ISSUE TITLE
Fisher doesn't compile on macOS

### ISSUE THREAD

**Issue by pietroalbini** [pietroalbini/fisher#13]
Fisher currently uses the `signal` crate for signal handling, but it doesn't like macOS so much. While supporting macOS is not one of my goals (mainly because I'm unable to test on it), switching to `nix` (which supports macOS) for signal handling is quite easy (and it removes a dependency), so why not.

**Comment by pietroalbini** [comment]
@piaoger could you please test if the [remove-signal-crate](https://github.com/pietroalbini/fisher/tree/remove-signal-crate) branch works fine on macOS? Thanks!

**Comment by piaoger** [comment]
@pietroalbini  I have tested the branch and it works very well. Just merge it to master 💯

**Comment by pietroalbini** [comment]
Merged it! Thanks for testing the branch.
