### ISSUE TITLE
Hooks containing dots don't work

### ISSUE THREAD

**Issue by paolobarbolini** [pietroalbini/fisher#6]
Hooks containing a dot in the name of the file don't work despite the fact that they get displayed in collected hooks when starting fisher (tested on 1.0.0-beta.2)

### Steps to reproduce
1. Create a hook containing a dot in the name of the file, for example ``test.something.sh``
2. Start fisher
3. Run ``curl http://127.0.0.1:8000/hook/test.something``
4. The response is ``{"status":"not_found"}``

**Comment by pietroalbini** [comment]
This is a problem with Nickel, the web framework Fisher is currently using: it doesn't accept dots in path fragments. I was already planning to replace it with tiny_http, so the bug should be fixed when I complete the transition to it.

**Comment by pietroalbini** [comment]
The fix for this is now in the `feature/optimize` branch, it will be merged on master soon*ish*.
